// @generated by protobuf-ts 2.9.1 with parameter optimize_code_size,output_typescript,long_type_bigint,server_grpc1,server_generic
// @generated from protobuf file "protos/greet.proto" (package "greet.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { GreetService } from "./greet";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GreetResponse } from "./greet";
import type { GreetRequest } from "./greet";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service greet.v1.GreetService
 */
export interface IGreetServiceClient {
    /**
     * @generated from protobuf rpc: Hello(greet.v1.GreetRequest) returns (greet.v1.GreetResponse);
     */
    hello(input: GreetRequest, options?: RpcOptions): UnaryCall<GreetRequest, GreetResponse>;
    /**
     * @generated from protobuf rpc: Hi(greet.v1.GreetRequest) returns (stream greet.v1.GreetResponse);
     */
    hi(input: GreetRequest, options?: RpcOptions): ServerStreamingCall<GreetRequest, GreetResponse>;
}
/**
 * @generated from protobuf service greet.v1.GreetService
 */
export class GreetServiceClient implements IGreetServiceClient, ServiceInfo {
    typeName = GreetService.typeName;
    methods = GreetService.methods;
    options = GreetService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Hello(greet.v1.GreetRequest) returns (greet.v1.GreetResponse);
     */
    hello(input: GreetRequest, options?: RpcOptions): UnaryCall<GreetRequest, GreetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GreetRequest, GreetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Hi(greet.v1.GreetRequest) returns (stream greet.v1.GreetResponse);
     */
    hi(input: GreetRequest, options?: RpcOptions): ServerStreamingCall<GreetRequest, GreetResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GreetRequest, GreetResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
